### ISSUE TITLE
Match regular expressions only at the beginning.

### ISSUE THREAD

**Issue by jessitron** [atomist/microgrammar#14]
Clay and I lost at least half an hour and a lot of brainpower today figuring out that we have to put a ^ in front of our regexp unless we want it to mean "anything up to and including a match to this regexp."

That is not what a regex matcher should mean; if I wanted that I'd use a Break (including terminal match). 

This is the second time I've suffered from extreme confusion on this, and it'll be at least as bad for users.

I propose we prepend a ^ to all regex that don't have them already. Or require it and give an error if they forget. (either in the existing constructor or in a convenient factory method.)

**Comment by jessitron** [comment]
cc: @claymccoy

**Comment by johnsonr** [comment]
I agree that the present behavior is not what users will expect. We should change it so that adding an anchor if there isn't one is the default, but the present behavior can be accessed with config (e.g. `new Regex(/pattern/).deAnchor`

**Comment by johnsonr** [comment]
Fixed in `master`
