### ISSUE TITLE
Error inside microgrammar module when I try to use it

### ISSUE THREAD

**Issue by jessitron** [atomist/microgrammar#2]
When trying to use these in a Rug (here: https://github.com/satellite-of-love/elm-rug-language-extension/blob/master/.atomist/editors/MicrogrammarUpdateMainString.ts)

I get this error in rug test. Not sure what to make of this:
```
    | | └── Scenario aborted: Could not evaluate: [Editor 'MicrogrammarUpdateMainString' failed due to [Microgrammar_1.Microgrammar is not a function] at .atomist/node_modules/@atomist/microgrammar/MicrogrammarSpecParser.js:56/1
    | |             return new Microgrammar_1.Microgrammar(concat, config);
    | |     ^]
```

**Comment by cdupuis** [comment]
That is usually an indication for a cyclic import. Those only show when we run things on Nashorn.

**Comment by ddgenome** [comment]
`@atomist/microgrammar` 0.2.0 is working under `rug test` in other Rug projects. I cannot reproduce this error:

```
$ rug test -urX
Resolving dependencies for jessitron:scala-project (0.1.0·local) failed

com.atomist.rug.cli.RunnerException: Failed to resolve or download dependencies:
  com.atomist:rug-cli-root:jar:1.0.0
  └── com.jessitron:elm-parser-demo:jar:0.1.0 ← missing or unable to download
...
```

**Comment by johnsonr** [comment]
I fixed a cyclic import 2 days ago. I think it probably caused this. @jessitron when you get a chance, can you retest the current version?

**Comment by jessitron** [comment]
I don't have the code to retry this but it's working in Nashorn in other places, it'll be fine
