### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by kristianmandrup** [atomist/microgrammar#33]
Hi there,

I'd be interested in getting started writing Rugs for Node.js and Javascript/Typescript in general.
I've taken a look at your blog posts and the [elm-rugs](https://github.com/jessitron/elm-rugs) by Jessica. However, I suspect that she is relying on en elm-grammar that I don't seem to be able to find. What are the layers needed for the Rug DSL to work on a new language?

Are there any Javascript/Typescript rugs out there or a grammar to work from (very similar to Java!).
Would anyone be interested to help out?

Thanks.

**Comment by johnsonr** [comment]
The elm stuff is old. I'd recommend my Java/Kotlin blog [here](https://the-composition.com/atomist-generator-deep-dive-c122561f6449) as a good guide to working with a language. I see you've found the ANTLR support. Please see my comments there. Will close this as an issue unless you have specific suggestions on how to improve the onboarding experience for this project.

**Comment by kristianmandrup** [comment]
Thanks a lot. Just wish you could dive a bit deeper into this statement:

_Atomist path expressions can work on any AST that exposes the simple TreeNode interface. Currently we build ASTs using microgrammars and ANTLR grammars, but this is user extensible._

From there it would be smooth sailing... I think I will try the micro grammar approach, implementing the TreeNode interface somehow to allow for the Path expressions to search for matches.

**Comment by johnsonr** [comment]
TreeNodes are already integrated with microgrammars. See `microgrammarsTest` in `automation-client-ts`.  This is the approach I mentioned in our discussion in `antlr-ts`. I wonder if for TypeScript you could use the TypeScript parser and create a TreeNode from that. `MicrogrammarBasedFileParser` could serve as a model.

Good luck!

**Comment by kristianmandrup** [comment]
Thanks a lot for the tips. I’ll look into it shortly when I find the time... How do I join Atomist? How about an invite to your public Atomist slack channel? Thanks again!

**Comment by kristianmandrup** [comment]
In which project can I find MicrogrammarBasedFileParser? In microgrammars?

**Comment by kristianmandrup** [comment]
Ah, found it here

https://github.com/atomist/automation-client-ts/blob/master/src/tree/ast/microgrammar/MicrogrammarBasedFileParser.ts

**Comment by kristianmandrup** [comment]
So it would seem the key is to make the: isTreePatternMatch return true on a microgrammar match as it traverses the file.... to build up the tree recursively. It uses a generic Path matcher so I would have to supply my own?

**Comment by jessitron** [comment]
hmm. there should be a Path matcher somewhere. We haven't broken these out into projects carefully yet, as we're letting it stabilize first. There should be a Path Expression path matcher of some sort. @johnsonr  will know where it is

**Comment by kristianmandrup** [comment]
Hi Jessica ;)

Yes, there is one:

```
import { isTreePatternMatch, PatternMatch } from "@atomist/microgrammar/PatternMatch";
```

_Represents a successful match_ [PatternMatch.ts](https://github.com/atomist/microgrammar/blob/master/src/PatternMatch.ts)

 _Represents a complex pattern match._ `TreePatternMatch extends PatternMatch`

Wouldn't I have to customise or override it? Where is my entry point to customise this `MicrogrammarBasedFileParser`?

Looking at the tests for it... [MicrogrammarBasedFileParserTest.ts](https://github.com/atomist/automation-client-ts/blob/master/test/tree/ast/microgrammar/MicrogrammarBasedFileParserTest.ts)

So I just pass it my microgrammar and it should work, but how do I make it recursive to return a full tree of matches? I guess I would need to have a nested grammar of some sort?

```js
    it("should parse a file", done => {
        const f = new InMemoryFile("Thing", "Tom:16 Mary:25");
        const mg = Microgrammar.fromString<Person>("${name}:${age}", {
            age: Integer,
        });

        new MicrogrammarBasedFileParser("people", "person", mg)
            .toAst(f)
            .then(root => {
                console.log(JSON.stringify(root, null, 2));
                assert(root.$name === "people");
                assert(root.$children.length === 2);
                const tom = root.$children[0] as TreeNode;
                // console.log(JSON.stringify(tom));
                assert(tom.$name === "person");
                assert(tom.$children.length === 2);
                done();
            }).catch(done);
    });
```

**Comment by jessitron** [comment]
A nested grammar: that is how we usually do it, yes. almost everything is a TreePatternMatch.

Here's an example with a nested grammar -- is this helpful?

https://github.com/atomist/automation-client-ts/blob/64cc609fded9d24ee4861ab075f07503423f678e/test/tree/ast/microgrammar/MicrogrammarBasedFileParserTest.ts#L86

**Comment by kristianmandrup** [comment]
Perfect! Exactly what I thought :) 
Now I'm on the right track I think... 
Hope you will write a blog post on this soon or improve the docs a little in this regard. 

Thanks again @jessitron and @johnsonr :)

**Comment by johnsonr** [comment]
The generic path matching support will work on _any_ `TreeNode` implementation. Should even allow replace if you've exposed positions.

**Comment by johnsonr** [comment]
I'm excited about the thought of exposing the TypeScript AST from the parser this way, as per your post in `antlr-ts`

**Comment by kristianmandrup** [comment]
I might try to use this

https://github.com/dsherret/ts-simple-ast

**Comment by johnsonr** [comment]
Please see https://github.com/atomist/automation-client-ts/issues/77

I think we can wrap the AST from the parser directly. It's already running path expressions with our generic path expression engine.
