### ISSUE TITLE
1.0.0-M4 released in namespace @atomist/microgrammar/lib/Microgrammar

### ISSUE THREAD

**Issue by ludovicc** [atomist/microgrammar#38]
It used to be @atomist/microgrammar/Microgrammar

**Comment by cdupuis** [comment]
This should now be imported from `@atomist/microgrammar`.

**Comment by ddgenome** [comment]
We've migrated to a more standard Node.js package layout and import paradigm.

**Comment by ludovicc** [comment]
Ok, that's the kind of information that should appear in the changelog...

**Comment by ddgenome** [comment]
Sorry, it was in a previous release https://github.com/atomist/microgrammar/blob/master/CHANGELOG.md#090---2018-08-22 but probably was not explicit enough.
